# Generated by Django 5.1.7 on 2025-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=255)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=False)),
                ('auto_interval', models.IntegerField()),
                ('event_interval', models.IntegerField()),
            ],
        ),
    ]
