# Generated by Django 5.1.7 on 2025-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0002_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
