# Generated by Django 5.1.7 on 2025-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0003_alter_detectedimage_id_alter_sensordata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimage',
            name='head_count',
            field=models.IntegerField(default=0),
        ),
    ]
