# Generated by Django 5.1.7 on 2025-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0004_detectedimage_head_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='UartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IAQ', models.IntegerField()),
                ('PM2_5', models.IntegerField()),
                ('PM10', models.IntegerField()),
                ('CO2', models.IntegerField()),
                ('TVOC_Value', models.IntegerField()),
                ('TVOC_Index', models.IntegerField()),
                ('Viral_Value', models.IntegerField()),
                ('Viral_Index', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('Temperature_C', models.IntegerField()),
                ('Temperature_F', models.IntegerField()),
                ('PM1', models.IntegerField()),
            ],
        ),
    ]
