# Generated by Django 5.1.7 on 2025-04-29 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0005_uartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uartdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
