# Generated by Django 5.1.7 on 2025-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0006_uartdata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Module_Name', models.CharField(max_length=255)),
                ('Device_Name', models.CharField(max_length=255)),
                ('Button_Id', models.CharField(max_length=255)),
                ('Operation_Type', models.IntegerField()),
            ],
        ),
    ]
