# Generated by Django 5.1.7 on 2025-05-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0007_device_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_Device_Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Device_Name', models.CharField(max_length=255)),
                ('Button_Id', models.CharField(max_length=255)),
                ('Operation_Type', models.IntegerField()),
                ('Intensity_Value', models.IntegerField()),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device_permission',
            name='Button_Id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device_permission',
            name='Device_Name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
