# Generated by Django 5.1.7 on 2025-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0008_live_device_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Permission_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Name', models.CharField(max_length=255)),
                ('Button_Id', models.CharField(max_length=255)),
                ('Operation_Type', models.IntegerField()),
                ('Intensity_Value', models.IntegerField()),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
