# Generated by Django 5.1.7 on 2025-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_app', '0009_device_permission_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_permission',
            name='Intensity',
            field=models.IntegerField(default=0),
        ),
    ]
